# Generated by Django 4.1.7 on 2023-03-27 21:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Music",
            fields=[
                ("music_id", models.AutoField(primary_key=True, serialize=False)),
                ("music_name", models.CharField(default="", max_length=30)),
                ("singer", models.CharField(default="", max_length=30)),
                ("src", models.FileField(default=None, max_length=300, upload_to="")),
                ("marked_number", models.IntegerField(default="0")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(default="", max_length=20, unique=True)),
                ("user_phone", models.CharField(max_length=12)),
                ("user_password", models.CharField(max_length=32)),
                (
                    "created_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarkedScore",
            fields=[
                ("score_id", models.AutoField(primary_key=True, serialize=False)),
                ("score", models.IntegerField(default="")),
                ("mark_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "music_id",
                    models.ForeignKey(
                        db_column="music_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.music",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarkedClip",
            fields=[
                ("clip_id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.IntegerField(default="0")),
                ("end_time", models.IntegerField(default="0")),
                ("mark_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "music_id",
                    models.ForeignKey(
                        db_column="music_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.music",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.user",
                    ),
                ),
            ],
        ),
    ]
