# Generated by Django 4.1.7 on 2023-03-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_music_marked_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="markedclip",
            name="type",
            field=models.CharField(default="", max_length=30),
        ),
    ]
