# Generated by Django 4.1.7 on 2023-04-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_markedclip_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(default="", max_length=30, unique=True),
        ),
    ]
