# Generated by Django 4.1.7 on 2023-04-14 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_markedclip_score"),
    ]

    operations = [
        migrations.RenameField(
            model_name="markedclip", old_name="score", new_name="clip_score",
        ),
    ]
