# Generated by Django 4.1.7 on 2023-05-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_markedclip_clip_score_remove_markedclip_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="music",
            name="genre",
            field=models.CharField(default="", max_length=30),
        ),
        migrations.AddField(
            model_name="music",
            name="harmony_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
