# Generated by Django 4.1.7 on 2023-11-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_music_genre_music_harmony_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="markedclip",
            name="type",
            field=models.CharField(default="", max_length=30),
        ),
    ]
