# Generated by Django 4.1.7 on 2023-11-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_markedclip_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="markedclip",
            name="end_time",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="markedclip",
            name="start_time",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
