# Generated by Django 4.1.7 on 2023-11-23 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_markedclip_end_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignUserMusic",
            fields=[
                ("assign_id", models.AutoField(primary_key=True, serialize=False)),
                ("is_mark", models.IntegerField(default=0)),
                (
                    "music_id",
                    models.ForeignKey(
                        db_column="music_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.music",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.user",
                    ),
                ),
            ],
        ),
    ]
