# Generated by Django 5.0.6 on 2024-08-03 14:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0011_assignusermusic"),
    ]

    operations = [
        migrations.CreateModel(
            name="DimensionScore",
            fields=[
                (
                    "dimension_score_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("dimension", models.CharField(default="", max_length=30)),
                ("dimension_score", models.IntegerField(default=-1)),
                ("mark_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "music_id",
                    models.ForeignKey(
                        db_column="music_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.music",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.user",
                    ),
                ),
            ],
            options={
                "db_table": "DimensionScore",
            },
        ),
    ]
