# Generated by Django 5.0.6 on 2024-08-03 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_dimensionscore"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dimensionscore",
            old_name="dimension_score",
            new_name="score",
        ),
    ]
