# Generated by Django 5.0.6 on 2024-08-03 15:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0014_rename_score_dimensionscore_dimension_score"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dimensionscore",
            old_name="dimension_score",
            new_name="score",
        ),
    ]
