# Generated by Django 5.0.6 on 2024-08-03 15:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0015_rename_dimension_score_dimensionscore_score"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dimensionscore",
            old_name="score",
            new_name="dimension_score",
        ),
    ]
