# Generated by Django 5.0.6 on 2024-08-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0016_rename_score_dimensionscore_dimension_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="Music_Instrumental",
            fields=[
                ("music_id", models.AutoField(primary_key=True, serialize=False)),
                ("music_name", models.CharField(default="", max_length=30)),
                ("singer", models.CharField(default="", max_length=30)),
                ("genre", models.CharField(default="", max_length=30)),
                ("harmony_quantity", models.IntegerField(default=0)),
                ("src", models.FileField(default=None, max_length=300, upload_to="")),
                ("marked_number", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Music_Vocal",
            fields=[
                ("music_id", models.AutoField(primary_key=True, serialize=False)),
                ("music_name", models.CharField(default="", max_length=30)),
                ("singer", models.CharField(default="", max_length=30)),
                ("genre", models.CharField(default="", max_length=30)),
                ("harmony_quantity", models.IntegerField(default=0)),
                ("src", models.FileField(default=None, max_length=300, upload_to="")),
                ("marked_number", models.IntegerField(default=0)),
            ],
        ),
    ]
